### ISSUE TITLE
On generate bid process when reporting a win the function: "registerAdBeacon" doesn't exist.

### ISSUE THREAD

**Issue by guybashan** [android/privacy-sandbox-samples#132]
It seems like this function doesn't exist in the context of the execution of the JavaScript.

This is the exception I get:
```
Report Impression invocation failed!
                                                                                                    com.android.adservices.service.exception.JSExecutionException: Failure running JS in WebView: Uncaught ReferenceError: registerAdBeacon is not defined
                                                                                                    const queryString=queryParts.join("&");let clickUri=reporting_address+"/click";let viewUri=reporting_address+"/view";const beacons={click:clickUri,view:viewUri};registerAdBeacon(beacons);return{status:0,results:{reporting_uri:`${reporting_address}/report/win?${queryString}`}}}
                                                                                                    	at com.android.adservices.service.js.JSScriptEngine.lambda$evaluateOnSandbox$2(JSScriptEngine.java:437)
                                                                                                    	at com.android.adservices.service.js.JSScriptEngine.$r8$lambda$GLltnNbZibPbmqPQOPGPEsozNq8(JSScriptEngine.java:0)
                                                                                                    	at com.android.adservices.service.js.JSScriptEngine$$ExternalSyntheticLambda3.apply(R8$$SyntheticClass:0)
                                                                                                    	at com.google.common.util.concurrent.ClosingFuture$CloseableList.applyClosingFunction(ClosingFuture.java:2199)
                                                                                                    	at com.google.common.util.concurrent.ClosingFuture$7.apply(ClosingFuture.java:892)
                                                                                                    	at com.google.common.util.concurrent.ClosingFuture$7.apply(ClosingFuture.java:889)
                                                                                                    	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:203)
                                                                                                    	at com.google.common.util.concurrent.AbstractCatchingFuture$AsyncCatchingFuture.doFallback(AbstractCatchingFuture.java:190)
                                                                                                    	at com.google.common.util.concurrent.AbstractCatchingFuture.run(AbstractCatchingFuture.java:133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: androidx.javascriptengine.EvaluationFailedException: Uncaught ReferenceError: registerAdBeacon is not defined
                                                                                                    const queryString=queryParts.join("&");let clickUri=reporting_address+"/click";let viewUri=reporting_address+"/view";const beacons={click:clickUri,view:viewUri};registerAdBeacon(beacons);return{status:0,results:{reporting_uri:`${reporting_address}/report/win?${queryString}`}}}
                                                                                                    	at androidx.javascriptengine.JavaScriptIsolate.handleEvaluationError(JavaScriptIsolate.java:473)
                                                                                                    	at androidx.javascriptengine.JavaScriptIsolate$IJsSandboxIsolateSyncCallbackStubWrapper.lambda$reportErrorWithFd$1(JavaScriptIsolate.java:144)
                                                                                                    	at androidx.javascriptengine.JavaScriptIsolate$IJsSandboxIsolateSyncCallbackStubWrapper.$r8$lambda$1hfkAVo3DNg6EKHkJKRJo8IcyVw(JavaScriptIsolate.java:0)
                                                                                                    	at androidx.javascriptengine.JavaScriptIsolate$IJsSandboxIsolateSyncCallbackStubWrapper$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
                                                                                                    	... 3 more
```

This is the relevant code in the reportWin function:

```
    let clickUri = reporting_address + '/click';
    let viewUri = reporting_address + '/view';
    const beacons = {'click': clickUri, 'view': viewUri};
    registerAdBeacon(beacons);
```

**Comment by c4mb0t** [comment]
Hello,
It sounds like you may need to enable the flag for registerAdBeacon:

```
adb shell device_config put adservices fledge_register_ad_beacon_enabled true
```

Check out the [Before you begin](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience/android/developer-guide/index.md#you-begin) section of the Protected Audience docs to make sure all the flags you need are enabled, or try the [adservices_cli tool](https://github.com/privacysandbox/dev-tools/tree/main/adservices_cli) to enable them programmatically.

**Comment by guybashan** [comment]
> Hello, It sounds like you may need to enable the flag for registerAdBeacon:
> 
> ```
> adb shell device_config put adservices fledge_register_ad_beacon_enabled true
> ```
> 
> Check out the [Before you begin](https://developers.google.com/privacy-sandbox/private-advertising/protected-audience/android/developer-guide/index.md#you-begin) section of the Protected Audience docs to make sure all the flags you need are enabled, or try the [adservices_cli tool](https://github.com/privacysandbox/dev-tools/tree/main/adservices_cli) to enable them programmatically.

Thanks! it seems to resolve the issue and now the JS code doesn't fail.
Any way I have of firing these events in order to test things enb-to-end?
