### ISSUE TITLE
When trying to load the SDK, getting the error

### ISSUE THREAD

**Issue by hellosagar** [android/privacy-sandbox-samples#14]
I've followed the steps mentioned in the readme but facing an error when clicking on the `Load SDK` button.

Steps I took to run the client app.
- First install the SDK-app
- Second, install the Client-app

Console Logs:

```
08/03 19:19:59: Launching 'client-app' on Pixel 4 API TiramisuPrivacySandbox.
Install successfully finished in 128 ms.
$ adb shell am start -n "com.example.privacysandbox.client/com.example.client.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 10227 on device 'Pixel_4_API_TiramisuPrivacySandbox [emulator-5554]'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/ysandbox.client: Late-enabling -Xcheck:jni
W/re-initialized>: type=1400 audit(0.0:97): avc: granted { execute } for path="/data/data/com.example.privacysandbox.client/code_cache/startup_agents/4cead168-agent.so" dev="dm-35" ino=139363 scontext=u:r:untrusted_app:s0:c161,c256,c512,c768 tcontext=u:object_r:app_data_file:s0:c161,c256,c512,c768 tclass=file app=com.example.privacysandbox.client
V/studio.deploy: Startup agent attached to VM
V/studio.deploy: No existing instrumentation found. Loading instrumentation from instruments-962d6e1a.jar
W/ysandbox.client: DexFile /data/data/com.example.privacysandbox.client/code_cache/.studio/instruments-962d6e1a.jar is in boot class path but is not in a known location
V/studio.deploy: Applying transforms with cached classes
W/ysandbox.client: Redefining intrinsic method java.lang.Thread java.lang.Thread.currentThread(). This may cause the unexpected use of the original definition of java.lang.Thread java.lang.Thread.currentThread()in methods that have already been compiled.
W/ysandbox.client: Redefining intrinsic method boolean java.lang.Thread.interrupted(). This may cause the unexpected use of the original definition of boolean java.lang.Thread.interrupted()in methods that have already been compiled.
D/CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10161; state: ENABLED
W/ziparchive: Unable to open '/data/app/~~fH2YBXYdC9T5l6YTvz-JHw==/com.example.privacysandbox.client-UFL2ik9anp7eT6gMfLTjBA==/base.dm': No such file or directory
W/ziparchive: Unable to open '/data/app/~~fH2YBXYdC9T5l6YTvz-JHw==/com.example.privacysandbox.client-UFL2ik9anp7eT6gMfLTjBA==/base.dm': No such file or directory
V/GraphicsEnvironment: ANGLE Developer option for 'com.example.privacysandbox.client' set to: 'default'
V/GraphicsEnvironment: ANGLE GameManagerService for com.example.privacysandbox.client: false
V/GraphicsEnvironment: Neither updatable production driver nor prerelease driver is supported.
I/LoadedApk: No resource references to update in package com.example.privacysandbox.provider
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/libEGL: loaded /vendor/lib64/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib64/egl/libGLESv2_emulation.so
D/CompatibilityChangeReporter: Compat change id reported: 195946584; UID 10161; state: ENABLED
W/ysandbox.client: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (unsupported, reflection, allowed)
W/ysandbox.client: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (unsupported, reflection, allowed)
D/CompatibilityChangeReporter: Compat change id reported: 210923482; UID 10161; state: ENABLED
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xb400007474d8f9d0, tid 10249
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
W/OpenGLRenderer: Failed to initialize 101010-2 format, error = EGL_SUCCESS
D/EGL_emulation: eglCreateContext: 0xb400007474d8e7d0: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xb400007474d8e7d0: ver 3 0 (tinfo 0x768f4f1080) (first time)
I/Gralloc4: mapper 4.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xb400007474d8ed10, tid 10249
D/goldfish-address-space: allocate: Ask for block of size 0x100
D/goldfish-address-space: allocate: ioctl allocate returned offset 0x1efff8000 size 0x8000
W/Gralloc4: allocator 4.x is not supported
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_vulkan_queue_submit_with_commands ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
D/EGL_emulation: app_time_stats: avg=325.53ms min=0.96ms max=3204.50ms count=11
D/CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10161; state: ENABLED
D/EGL_emulation: app_time_stats: avg=34.39ms min=0.91ms max=1338.36ms count=52
E/SandboxClient: Attempting to load sandbox SDK
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.privacysandbox.client, PID: 10227
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/sdksandbox/SdkSandboxManager$LoadSdkCallback;
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1283)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3574)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3818)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2301)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7849)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.sdksandbox.SdkSandboxManager$LoadSdkCallback" on path: DexPathList[[zip file "/data/app/~~fH2YBXYdC9T5l6YTvz-JHw==/com.example.privacysandbox.client-UFL2ik9anp7eT6gMfLTjBA==/base.apk"],nativeLibraryDirectories=[/data/app/~~fH2YBXYdC9T5l6YTvz-JHw==/com.example.privacysandbox.client-UFL2ik9anp7eT6gMfLTjBA==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Class.newInstance(Native Method) 
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
        at android.app.Instrumentation.newActivity(Instrumentation.java:1283) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3574) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3818) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:99) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2301) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7849) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
D/EGL_emulation: app_time_stats: avg=16.61ms min=13.65ms max=20.24ms count=61
```

**Comment by hellosagar** [comment]
I've testing it on
 - Pixel 4 API Tiramisu Privacy Sandbox

**Comment by cshmerling** [comment]
Which revision of the emulator image and SDK are you using? Can you try updating to the latest if you are not on Revision 6?

**Comment by hellosagar** [comment]
@cshmerling Revision 6 of what exactly?

**Comment by cshmerling** [comment]
Both the Privacy Sandbox SDK and Device Images. I've run in to the error your describing when there was some version mismatch between them, so want to confirm you are using the latest of everything before I dig further.

In Tools > SDK manager:

![image](https://user-images.githubusercontent.com/106990149/182687973-1c818436-8557-4818-a6b9-15221fae4ddc.png)
 both should be revision 6. Then you might need to create a new virtual device using the latest emulator image

**Comment by hellosagar** [comment]
@cshmerling Thanks man, I wasted hours on this, when I opened the SDK Platforms it had different versions but it definitely not both 6 on each, now I've downloaded it and created an emulator from scratch and finally SDK loaded 
Thanks again 🫡🫡🫡

<img width="424" alt="Screenshot 2022-08-04 at 2 18 48 AM" src="https://user-images.githubusercontent.com/50016799/182708801-ff4f3730-b429-4986-b074-cc812d5465dc.png">
