### ISSUE TITLE
Confirm dev environment for Attribution Sample App

### ISSUE THREAD

**Issue by levyitay** [android/privacy-sandbox-samples#31]
Hi, 
I have been trying to build and run the Attribution Sample App. 
It looks like the build isn't successful and throws an error on the latest canary and AGP. 
Also on stable Dolphin with the provided AGP and gradle wrapper, it does succeed in being built but throws a bunch of warnings like:
`unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>`

Lastly on the latest preview image for pixel 5 and on the latest Preview Emulator image rev. 8 the app cannot find the Ad Service and throws an exception:
```
 E  FATAL EXCEPTION: main
Process: com.example.measurement.sampleapp, PID: 25303
java.lang.IllegalStateException: Service is not available.
at com.android.adservices.AndroidServiceBinder.getService(AndroidServiceBinder.java:146)
at android.adservices.adid.AdIdManager.getService(AdIdManager.java:92)
at android.adservices.adid.AdIdManager.getAdId(AdIdManager.java:124)
at android.adservices.measurement.MeasurementManager.registerSource(MeasurementManager.java:203)
```

**Comment by erintwalsh** [comment]
Hi @levyitay, thanks for bringing this to our attention! We are working on addressing the build errors. 

In the meantime, you can avoid the fatal exception error by running this adb command: 

`adb shell device_config put adservices global_kill_switch false`

You can check out our [documentation](https://developer.android.com/design-for-safety/privacy-sandbox/setup-api-access#enable-access) for more context.

**Comment by erintwalsh** [comment]
Hi @levyitay, thanks for bringing this to our attention! We are working on addressing the build errors on latest Android Studio Canary.

The fatal exception error can be avoided by running this adb command:

`adb shell device_config put adservices global_kill_switch false`

You can find more context on our [documentation here](https://developer.android.com/design-for-safety/privacy-sandbox/setup-api-access#enable-access).

**Comment by levyitay** [comment]
Thanks @erintwalsh for some reason I missed that step. 
BTW it stopped crashing only when I ran the step you mentioned in the following way:
```
adb shell
device_config put adservices global_kill_switch false
```  

So now it's not crashing but, when trying to run
`adb shell cmd jobscheduler run -f com.google.android.adservices.api 5`
or any other job number I'm getting:
`Could not find job 5 in package com.google.android.adservices.api / user 0`

Any idea what could have caused this?

**Comment by erintwalsh** [comment]
Hi @levyitay, 

Have you done all of these steps? 

1. Added the app to the allow list
`adb shell device_config put adservices ppapi_app_allow_list \"*\"`

2. Enabled Privacy-Preserving API access 
`adb shell device_config put adservices global_kill_switch false`

3. Toggled on debug consent mode
`adb shell setprop debug.adservices.consent_manager_debug_mode true`

Please let us know if you have done these and are still getting the error!

**Comment by levyitay** [comment]
@erintwalsh yes I did.
Wouldn't it be more of the `com.google.android.adservices.api` doesn't have the job scheduled or something like that?
maybe the last rev (8) of the image caused it?

**Comment by erintwalsh** [comment]
@levyitay Yes - the jobs aren't scheduled unless all three of the adb commands are run. Would you mind telling me more about your environment and tooling? Are you seeing `Could not find job` on stable Dolphin, Canary, or both? Which device(s) are you seeing this error with?

**Comment by levyitay** [comment]
@erintwalsh 
```
127|redfin:/ $ device_config get adservices ppapi_app_allow_list                                                                                                                                                        
*
redfin:/ $ device_config get adservices global_kill_switch
false
redfin:/ $ getprop debug.adservices.consent_manager_debug_mode                                                                                                                                                          
true
redfin:/ $ cmd jobscheduler run -f com.google.android.adservices.api 5
Could not find job 5 in package com.google.android.adservices.api / user 0
23|redfin:/ $ 
```
I'm using Android Studio Flamingo | 2022.2.1 Canary 8
With Pixel 5 that has preview image installed 
```
[ro.vendor_dlkm.build.id]: [TRA4.221021.001.A1]
```

**Comment by erintwalsh** [comment]
Hi @levyitay, 

Thank you for your patience while we work out this issue! I just wanted to check, have you registered a source and a trigger before trying to force the job? The jobs are unable to be scheduled until the API is called.

**Comment by levyitay** [comment]
Hi @erintwalsh I saw that the code and some instructions were updated.
I'm going to try again from scratch and if all works ill close the issue.

**Comment by cshmerling** [comment]
@levyitay are you still experiencing this issue?

**Comment by siran-work** [comment]
It has been a while since our last response.

We will mark this issue with a standard status: “Fixed”. If you wish to provide additional feedback or discuss our response further, please create another issue

**Comment by cshmerling** [comment]
Closing due to inactivity. Please re-open this issue if you encounter the problem again.

**Comment by levyitay** [comment]
@cshmerling works now, still didn't get any postback but it might be an enrollment issue as we are not getting any calls to our endpoint
