### ISSUE TITLE
Loading the example SDK fails in PrivacySandboxKotlin & PrivacySandboxJava

### ISSUE THREAD

**Issue by davidae** [android/privacy-sandbox-samples#38]
When initially running the `client-app`, following the guide in the `README.md`, having no local changes, the emulator (Pixel 2) is newly created, and I press "LOAD SDK" , it is often successful. I get the toast `"Loaded successfully!"`.

But when I try to make any changes to the code or re-run the application, it fails to load the SDK. I get the toast `"Load SDK Failed! null"`. 

If I extend the `LoadSdkCallbackImpl.onError(error: LoadSdkException)` with
```kt
override fun onError(error: LoadSdkException) {
	val state = SdkSandboxManager.getSdkSandboxState()
	log("SdkSandboxManager.getSdkSandboxState(): $state")

	log("error.extraInformation: "+error.extraInformation.toString())
	log("error.cause: "+error.cause.toString())
	log("error.toString(): $error")
	log("onLoadSdkFailure(" + error.loadSdkErrorCode.toString() + "): " + error.message)
	log("error.stackTraceToString(): "+error.stackTraceToString())
	makeToast("Load SDK Failed! " + error.message)
}
```

I get
```
E  SdkSandboxManager.getSdkSandboxState(): 2
E  error.extraInformation: Bundle[EMPTY_PARCEL]
E  error.cause: null
E  error.toString(): android.app.sdksandbox.LoadSdkException
E  onLoadSdkFailure(103): null
E  error.stackTraceToString(): android.app.sdksandbox.LoadSdkException
	at android.app.sdksandbox.LoadSdkException$1.createFromParcel(LoadSdkException.java:105)
	at android.app.sdksandbox.LoadSdkException$1.createFromParcel(LoadSdkException.java:102)
	at android.os.Parcel.readTypedObject(Parcel.java:3947)
	at android.app.sdksandbox.ILoadSdkCallback$Stub.onTransact(ILoadSdkCallback.java:102)
	at android.os.Binder.execTransactInternal(Binder.java:1285)
	at android.os.Binder.execTransact(Binder.java:1244)

```
`onLoadSdkFailure(103)` refers to [LOAD_SDK_SDK_SANDBOX_DISABLED](https://developer.android.com/design-for-safety/privacy-sandbox/reference/sdksandbox/SdkSandboxManager#LOAD_SDK_NOT_FOUND), which seems counter-intuitive since `getSdkSandboxState` is 2 ([SDK_SANDBOX_STATE_ENABLED_PROCESS_ISOLATION](https://developer.android.com/design-for-safety/privacy-sandbox/reference/sdksandbox/SdkSandboxManager#SDK_SANDBOX_STATE_ENABLED_PROCESS_ISOLATION))

# Current (tested) setups
- Ubuntu 20.04.5
- Android Studio - Flamingo Canary 7, 6, 2 (Not 8 given https://github.com/android/privacy-sandbox-samples/issues/33)
- I've tried using Rev 2, 6, and 8 of the `android-TiramisuPrivacySandbox` platform.

I use adb before running the application with the following configs
```
adb shell "device_config put adservices disable_fledge_enrollment_check true"
adb shell device_config put adservices disable_sdk_sandbox false
adb shell device_config put adservices ppapi_app_allow_list \"*\"
adb shell device_config put adservices global_kill_switch false
adb shell am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.AdServicesSettingsActivity
```

**Comment by serge-14** [comment]
This command helped us:

```
adb shell cmd sdk_sandbox set-state --enabled
```

You might need to run it every time when you start getting same error again.

**Comment by cshmerling** [comment]
I'll take the feedback about the confusing error state back and see if we can update anything to make that more clear. In terms of your issue, just want to make sure- after running that 
```
adb shell am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.AdServicesSettingsActivity
```

are you clicking the toggle to enable the sandbox?

If you are, can you generate a bug report with `adb bugreport` so I can share with the relevant folks?

**Comment by davidae** [comment]
> This command helped us:
> 
> ```
> adb shell cmd sdk_sandbox set-state --enabled
> ```
> 
> You might need to run it every time when you start getting same error again.

@serge-14, thank you for the tip, this workaround works :+1: But _sometimes_ it doesn't, but then
```
adb shell cmd sdk_sandbox stop com.example.privacysandbox.client
adb shell cmd sdk_sandbox start com.example.privacysandbox.client
```
seems to do the trick.

Interestingly, without doing the `stop` first I the following error
```
Error: Sdk sandbox already running for com.example.privacysandbox.client and user 0
```
It is somehow running but for the wrong user?

**Comment by davidae** [comment]
> I'll take the feedback about the confusing error state back and see if we can update anything to make that more clear. In terms of your issue, just want to make sure- after running that
> 
> ```
> adb shell am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.AdServicesSettingsActivity
> ```
> 
> are you clicking the toggle to enable the sandbox?

Yes

> 
> If you are, can you generate a bug report with `adb bugreport` so I can share with the relevant folks?

@cshmerling, I've generated a report now. How should I supply you or the 'relevant folks' with the `.zip` file?

**Comment by serge-14** [comment]
@davidae I also had an similar error, and then following code snippet helped me:

```
val sandboxedSdk = sdkSandboxManager.sandboxedSdks.find {
    it.sharedLibraryInfo.name == SDK_NAME
}

if (sandboxedSdk != null) {
    sdkSandboxManager.unloadSdk(SDK_NAME)
}

sdkSandboxManager.loadSdk(...)
```

**Comment by davidae** [comment]
@serge-14, thank you for this snippet, it works :clinking_glasses:

**Comment by cshmerling** [comment]
@davidae Forgot to include the link to our IssueTracker- can you upload the report and create an issue [here](https://issuetracker.google.com/issues/new?component=1116743&template=1642602)

I'm glad it got resolved, but would like to know more to see if this is something we can address- are the explicit steps to reproduce you can list? It seems like the order of operations is to start the client app, load the SDK, restart the client app, then it fails?

**Comment by davidae** [comment]
> It seems like the order of operations is to start the client app, load the SDK, restart the client app, then it fails?

Yes. I think I narrowed down the problem a bit now. I also got an issue when trying to j[oin a custom audience via CustomAudienceManager](https://developer.android.com/design-for-safety/privacy-sandbox/reference/adservices/customaudience/CustomAudienceManager#joinCustomAudience(android.adservices.customaudience.JoinCustomAudienceRequest,%20java.util.concurrent.Executor,%20android.os.OutcomeReceiver%3Cjava.lang.Object,%20java.lang.Exception%3E)). I got 
```
java.lang.IllegalStateException: Service is not available.
```

So, after a bit of debugging I realized that after calling
```
adb shell device_config put adservices disable_fledge_enrollment_check true
adb shell device_config put adservices adservice_system_service_enabled true
adb shell device_config put adservices disable_sdk_sandbox false
adb shell device_config put adservices adservice_enabled true
adb shell device_config put adservices global_kill_switch false
adb shell device_config put adservices ppapi_app_allow_list \"*\"
adb shell am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.AdServicesSettingsActivity
```
on a fresh emulator boot and calling this command
```
watch -d -n 1 "adb shell device_config list | grep 'adservices' | grep -ve 'measurement_\|topics_\|mdd_\|fledge_'"
```
I see
```
adservices/adservice_enabled=true
adservices/adservice_system_service_enabled=true
adservices/disable_sdk_sandbox=false
adservices/global_kill_switch=false
adservices/ppapi_app_allow_list=*
```

but if I leave the application running, at one point it changes to this
```
adservices/adid_kill_switch=false
adservices/adservice_enabled=false
adservices/adservice_system_service_enabled=false
adservices/appsetid_kill_switch=false
adservices/disable_sdk_sandbox=true
adservices/enrollment_blocklist_ids=
adservices/foreground_validation_status_level=125
adservices/global_kill_switch=true
adservices/ppapi_app_allow_list=android.platform.test.scenario,android.adservices.crystalball,androi
d.adservices.cts,android.adservices.debuggablects,com.android.adservices.endtoendtest,com.android.ad
services.servicecoretest,com.android.adservices.tests.permissions.appoptout,com.android.adservices.t
ests.permissions.valid,com.android.sdksandboxclient,com.android.tests.sandbox.adid,com.android.tests
.sandbox.appsetid,com.android.adservices.tests.adid,com.android.adservices.tests.appsetid,com.androi
d.tests.sandbox.fledge,com.android.tests.sandbox.measurement,com.example.adservices.samples.adid.app
,com.example.adservices.samples.appsetid.app,com.example.adservices.samples.fledge.sampleapp,com.exa
mple.adservices.samples.fledge.sampleapp1,com.example.adservices.samples.fledge.sampleapp2,com.examp
le.adservices.samples.fledge.sampleapp3,com.example.adservices.samples.fledge.sampleapp4,com.example
.measurement.sampleapp,com.example.measurement.sampleapp2,com.android.adservices.tests.cts.endtoendt
est.measurement,com.google.corp.bizapps.rews.food.android,com.google.corp.moma.android
adservices/ppapi_app_signature_allow_list={{SOME_ID}}
```

This was a particular issue to me since I've created a new package naming structure that isn't found in the `ppapi_app_allow_list`.

**Comment by cshmerling** [comment]
I've been looking in to this, and there might be a few things in play. 

The permissions are periodically reset, which I haven't gotten any clear updates on if there is a way to make things stick. The best advice I can give there is making sure to run the UI command and enable the Privacy Sandbox before running your app to shorten the time between those two events as much as possible. 

Additionally, there may be some problems with the pattern matching from the `adb shell device_config put adservices ppapi_app_allow_list \"*\"` command. This may be resolved if instead of using the wildcard match you use your package name, but it looks like you may be doing that based on the allowlist present there?

**Comment by cshmerling** [comment]
@davidae are you still experiencing this issue?

**Comment by cshmerling** [comment]
Closing this due to inactivity. Please re-open if you are still experiencing the issue.
