### ISSUE TITLE
Compile PrivacySandboxJava against SDK 33 (Android T)

### ISSUE THREAD

**Issue by negara** [android/privacy-sandbox-samples#42]
Hello,
I want to compile PrivacySandboxJava sample app with Android T (SDK 33) to build apps that are runnable on API 33. However, after changing the buid.gradle by replacing compilePreviewSdk, targetPreviewSdk, and minPreviewSdk with compileSdk 33, targetSdk 33, and etc, sdk-implementation project fails to resolve symbols 'SandboxedSdkProvider', 'sandboxedSdk' and etc. 
Is there anything else I need to change to build apps for Android T?

**Comment by cshmerling** [comment]
Timely question- we just launched an SDK compatible with Tiramisu today.
In the SDK Manager, you should see Android Tiramisu, Extension Level 4. Download that and relevant emulator image if required.
If you resync the repo, target are updated to build against that. More information will be published on developer.android.com around this as well.

**Comment by negara** [comment]
Sounds great. However, it seems there still is a compatibility problem. I see that the gradle.bundle is now changed to use API 33 but at the same time I see the following error:
''SandboxedSdk(android.os.IBinder)' in 'android.app.sdksandbox.SandboxedSdk' cannot be applied to '(com.example.sdkimplementation.SdkApi)''

**Comment by cshmerling** [comment]
I'm having trouble repro'ing the error- can you try a fresh clone of the repository and if the error persists include more of the build output? I'm wondering if since we had to update the main branch to some specific versions of files if there is a problem trying to pull that in to an existing copy of the repo

**Comment by cshmerling** [comment]
Also, just to make sure, are you using the latest Android Studio Canary? This project requires some features currently only available in Canary, with one known issue and fix in https://github.com/android/privacy-sandbox-samples/issues/43

**Comment by negara** [comment]
Thank you for the comments. How can I get the latest Android Studio Canary? I see in #43 Android Canary 11 is used. However, on my side, Canary 6 seems to be the latest when following steps [here](http://go/intellij-getting-started#installing-and-launching-an-ide).

**Comment by negara** [comment]
Thank you for the comments. How can I get the latest Android Studio Canary? I see in #43 Android Canary 11 is used. However, on my side, Canary 6 seems to be the latest.

**Comment by cshmerling** [comment]
You can download the latest Canary (Currently Flamingo 11) [here](https://developer.android.com/studio/preview)

**Comment by negara** [comment]
Thank you for the help :) I confirm that I was able to build and isntall two apps: client.apk and standalone.apk. However, when I click on load sdk, the app craches and I see the following error: 

```
comm.example.privacysandbox.client    E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.privacysandbox.client, PID: 17499
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/app/sdksandbox/SdkSandboxManager$SdkSandboxProcessDeathCallback;
                                                                                                    	at java.lang.Class.newInstance(Native Method)
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1339)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.app.sdksandbox.SdkSandboxManager$SdkSandboxProcessDeathCallback" on path: DexPathList[[zip file "/data/app/~~VFVYkBYcE4saxb1hpbyvnA==/com.example.privacysandbox.client-Hbjnr6eWGfnES26ifggOJg==/base.apk"],nativeLibraryDirectories=[/data/app/~~VFVYkBYcE4saxb1hpbyvnA==/com.example.privacysandbox.client-Hbjnr6eWGfnES26ifggOJg==/lib/x86_64, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.Class.newInstance(Native Method) 
                                                                                                    	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95) 
                                                                                                    	at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45) 
                                                                                                    	at android.app.Instrumentation.newActivity(Instrumentation.java:1339) 
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3538) 
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3782) 
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7872) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
```

**Comment by negara** [comment]
Given the following warnig and the error above, I think a newer AGP version is needed to include privacy sandbox (currently as discussed in #43 I am using 8.0.0-alpha10). 

> This warning can be suppressed by adding
    android.suppressUnsupportedCompileSdk=33
to this project's gradle.properties

The build will continue, but you are strongly encouraged to update your project to
use a newer Android Gradle Plugin that has been tested with compileSdk = 33

I appreciate any help :)

**Comment by cshmerling** [comment]
I'm forwarding this issue to the relevant people, hopefully can have an update in the near future.

**Comment by cshmerling** [comment]
And just to confirm- are you using a physical device or an emulator? Either way, are you using a device image we shipped with the Beta?

**Comment by negara** [comment]
emulator. To which device image are you referring? I am using the API 33 to create the device.

**Comment by cshmerling** [comment]
You'll need to download one of the emulator images included in the SDK 33, Extension Level 4 section of the SDK manager (depending on if you are using an ARM or an x86 machine)
![image](https://user-images.githubusercontent.com/106990149/212400307-37a064bf-40e5-4188-b5f2-f0d2a29c7095.png)

Then you'll need to create a device with that image. The device needs to be Play store enabled, so something like the Pixel 4 would work. Sometimes the right image doesn't show up in "recommended", but will show up under the specific tab
![image](https://user-images.githubusercontent.com/106990149/212400705-2c2563fc-c9c1-4705-8093-336c5f904a7f.png)

Make sure you create the device with the Tiramisu (Extension Level 4) image.

**Comment by negara** [comment]
Thank you for the help. The image was not shown under Recommended. 
Now, with the new image, I am able to build apps and the client app does not crash after clicking LOAD SDK. However, it returns "load sdk failed null" and in logcat I see: 

> Attempting to load sandbox SDK
2023-01-13 23:15:04.037 11297-11330 SandboxClient           
com.example.privacysandbox.client    E  onLoadSdkFailure(103): null

Thank you so much for being patient and helping me.

**Comment by cshmerling** [comment]
Apologies for the delay. Turns out there is only one command that is needed to enable the Privacy Sandbox on the emulator. Try running:
`adb shell cmd sdk_sandbox set-state --enabled`

And then load the SDK. If you are still getting an error, please run `adb shell dumpsys sdk_sandbox` and reply with the output here. Otherwise, feel free to mark this issue resolved if it is in fact resolved.

**Comment by negara** [comment]
I confirm that using this command, I was able to successfully work with app.
