### ISSUE TITLE
Getting service not available error while running Fledge Project

### ISSUE THREAD

**Issue by asifrahiman** [android/privacy-sandbox-samples#45]
Getting the below error while running the Fledge Kotlin project 
`2023-01-26 12:00:17.823 15896-15956 adservices              com...ices.samples.fledge.sampleapp  E  onNullBinding android.adservices.adselection.AD_SELECTION_SERVICE
2023-01-26 12:00:17.876 15896-15990 FledgeSample            com...ices.samples.fledge.sampleapp  E  java.lang.IllegalStateException: Service is not available.
                                                                                                    java.lang.IllegalStateException: Service is not available.
                                                                                                    	at com.android.adservices.AndroidServiceBinder.getService(AndroidServiceBinder.java:146)
                                                                                                    	at android.adservices.adselection.AdSelectionManager.getService(AdSelectionManager.java:99)
                                                                                                    	at android.adservices.adselection.TestAdSelectionManager.overrideAdSelectionConfigRemoteInfo(TestAdSelectionManager.java:70)
                                                                                                    	at com.example.adservices.samples.fledge.clients.TestAdSelectionClient.overrideAdSelectionConfigRemoteInfo$lambda-0(TestAdSelectionClient.kt:49)
                                                                                                    	at com.example.adservices.samples.fledge.clients.TestAdSelectionClient.$r8$lambda$IBu6ob0j-XDiUGmiBQsb4wncjZg(Unknown Source:0)
                                                                                                    	at com.example.adservices.samples.fledge.clients.TestAdSelectionClient$$ExternalSyntheticLambda2.attachCompleter(Unknown Source:4)
                                                                                                    	at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102)
                                                                                                    	at com.example.adservices.samples.fledge.clients.TestAdSelectionClient.overrideAdSelectionConfigRemoteInfo(TestAdSelectionClient.kt:48)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.AdSelectionWrapper.overrideAdSelection(AdSelectionWrapper.kt:124)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.useOverrides(MainActivity.kt:321)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.setupOverrideFlow(MainActivity.kt:196)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.onCreate(MainActivity.kt:130)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8290)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8269)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3657)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3813)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2308)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
2023-01-26 12:00:17.888 15896-15956 adservices              com...ices.samples.fledge.sampleapp  E  onNullBinding android.adservices.customaudience.CUSTOM_AUDIENCE_SERVICE
2023-01-26 12:00:17.912 15896-15956 adservices              com...ices.samples.fledge.sampleapp  E  onNullBinding android.adservices.customaudience.CUSTOM_AUDIENCE_SERVICE
2023-01-26 12:00:17.932 15896-15956 adservices              com...ices.samples.fledge.sampleapp  E  onNullBinding android.adservices.customaudience.CUSTOM_AUDIENCE_SERVICE
2023-01-26 12:00:17.952 15896-15956 adservices              com...ices.samples.fledge.sampleapp  E  onNullBinding android.adservices.customaudience.CUSTOM_AUDIENCE_SERVICE`

**Comment by asifrahiman** [comment]
Hi,
We are using Flemingo Canary 10 Android studio with sdk version Android TiramisuPrivacySandbox Preview and system image Tiramisu (Extension level 4).
We have used the below adb shell commands to enable privacy sandbox:
`device_config put adservices ppapi_app_allow_list \"*\"
device_config put adservices ppapi_app_signature_allow_list \"*\"
device_config put adservices adservice_system_service_enabled true
device_config put adservices adservice_enabled true
device_config put adservices adservice_enable_status true
device_config put adservices global_kill_switch false
device_config put adservices disable_sdk_sandbox false
device_config put adservices fledge_js_isolate_enforce_max_heap_size false
setprop debug.adservices.disable_fledge_enrollment_check true
am start -n com.google.android.adservices.api/com.android.adservices.ui.settings.AdServicesSettingsActivity
cmd sdk_sandbox set-state --enabled`

We are now getting the error:
`2023-01-28 12:17:56.433 15896-15896 JavaBinder              com...ices.samples.fledge.sampleapp  E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 552)
2023-01-28 12:17:56.435 15896-15896 adservices              com...ices.samples.fledge.sampleapp  E  Exception: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
2023-01-28 12:17:56.508 15896-28948 FledgeSample            com...ices.samples.fledge.sampleapp  E  Exception during CA join process 
                                                                                                    java.lang.IllegalStateException: Internal Error!
                                                                                                    	at android.adservices.customaudience.CustomAudienceManager.joinCustomAudience(CustomAudienceManager.java:167)
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.joinCustomAudience$lambda-0(CustomAudienceClient.kt:47)
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.$r8$lambda$1kleQWosdQ_op8_OKQdzfTT_bSo(Unknown Source:0)
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient$$ExternalSyntheticLambda0.attachCompleter(Unknown Source:4)
                                                                                                    	at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102)
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.joinCustomAudience(CustomAudienceClient.kt:43)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.CustomAudienceWrapper.joinCustomAudience(CustomAudienceWrapper.kt:219)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.CustomAudienceWrapper.joinCa(CustomAudienceWrapper.kt:80)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.setupCASwitches$lambda-1(MainActivity.kt:226)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.$r8$lambda$8R8R7-mZgaPzTO8jzeDCHJvgHio(Unknown Source:0)
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity$$ExternalSyntheticLambda3.onCheckedChanged(Unknown Source:12)
                                                                                                    	at android.widget.CompoundButton.setChecked(CompoundButton.java:222)
                                                                                                    	at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1071)
                                                                                                    	at androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1066)
                                                                                                    	at android.widget.CompoundButton.performClick(CompoundButton.java:144)
                                                                                                    	at android.view.View.performClickInternal(View.java:7483)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29335)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
                                                                                                    Caused by: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
                                                                                                    	at android.os.BinderProxy.transactNative(Native Method)
                                                                                                    	at android.os.BinderProxy.transact(BinderProxy.java:584)
                                                                                                    	at android.adservices.customaudience.ICustomAudienceService$Stub$Proxy.joinCustomAudience(ICustomAudienceService.java:211)
                                                                                                    	at android.adservices.customaudience.CustomAudienceManager.joinCustomAudience(CustomAudienceManager.java:147)
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.joinCustomAudience$lambda-0(CustomAudienceClient.kt:47) 
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.$r8$lambda$1kleQWosdQ_op8_OKQdzfTT_bSo(Unknown Source:0) 
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient$$ExternalSyntheticLambda0.attachCompleter(Unknown Source:4) 
                                                                                                    	at androidx.concurrent.futures.CallbackToFutureAdapter.getFuture(CallbackToFutureAdapter.java:102) 
                                                                                                    	at com.example.adservices.samples.fledge.clients.CustomAudienceClient.joinCustomAudience(CustomAudienceClient.kt:43) 
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.CustomAudienceWrapper.joinCustomAudience(CustomAudienceWrapper.kt:219) 
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.CustomAudienceWrapper.joinCa(CustomAudienceWrapper.kt:80) 
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.setupCASwitches$lambda-1(MainActivity.kt:226) 
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity.$r8$lambda$8R8R7-mZgaPzTO8jzeDCHJvgHio(Unknown Source:0) 
                                                                                                    	at com.example.adservices.samples.fledge.sampleapp.MainActivity$$ExternalSyntheticLambda3.onCheckedChanged(Unknown Source:12) 
                                                                                                    	at android.widget.CompoundButton.setChecked(CompoundButton.java:222) 
                                                                                                    	at androidx.appcompat.widget.SwitchCompat.setChecked(SwitchCompat.java:1071) 
                                                                                                    	at androidx.appcompat.widget.SwitchCompat.toggle(SwitchCompat.java:1066) 
                                                                                                    	at android.widget.CompoundButton.performClick(CompoundButton.java:144) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7483) 
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:29335) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7898) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
2023-01-28 12:17:57.208 15896-15896 JavaBinder              com...ices.samples.fledge.sampleapp  E  !!! FAILED BINDER TRANSACTION !!!  (parcel size = 304)
2023-01-28 12:17:57.209 15896-15896 adservices              com...ices.samples.fledge.sampleapp  E  Exception: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died, but this could also be caused by running out of binder buffe
2023-01-28 12:17:57.328 15896-15962 EGL_emulation           com...ices.samples.fledge.sampleapp  D  app_time_stats: avg=10.70ms min=3.68ms max=26.05ms count=59`

**Comment by cshmerling** [comment]
There are some incompatibilities between Developer Preview and Beta releases which may result in some binding issues. Can you try again a device image that matched with the compile SDK? 

If you want to use the Developer Preview builds, physical device images are available [here](https://developer.android.com/design-for-safety/privacy-sandbox/download?version=preview) and there are emulator images provided in Android Studio via the SDK Manager. Beta has physical device images [here](https://developer.android.com/design-for-safety/privacy-sandbox/download?version=beta), and the SDK and emulator images are also available in Android Studio via the SDK Manager.

If the error persists, can you please provide explicit steps to reproduce this error?

**Comment by cshmerling** [comment]
Also, can you confirm which version of the sample apps you are running? Are you using the `main` branch or `developer-preview-main`?

**Comment by cshmerling** [comment]
I think there are two issues here:

1. For the original FLEDGE issue, the mismatch between using the dev-preview-main and the system image for Tiramisu Extension Level 4. The dev-preview-main branch targets TiramisuPrivacySandboxPreview device images (aka Developer Preview) and the main branch targets Tiramisu Ext. Level 4 (aka Beta). I will update the documentation here to make that more clear.
2.  For the PrivacySandbocJava build issue, you can add `android.experimental.privacysandboxsdk.requireServices=false` to the project's `gradle.properties` file. I'm working to find a more permanent fix for that issue.

**Comment by asifrahiman** [comment]
Hi @cshmerling,
Thank you for the update. This has resolved both issues were facing. Hence closing this ticket.
