### ISSUE TITLE
Attribution - Getting "Failed to find resolveInfo for adServices service." 

### ISSUE THREAD

**Issue by levyitay** [android/privacy-sandbox-samples#46]
Hi Team, 
I'm trying to test the attribution process but keep getting the following error when I try to register source or trigger:
```
2023-01-30 15:55:27.412  5965-6441  adservices              com.google.android.adservices.api    E  Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
2023-01-30 15:55:27.412  5965-6441  adservices              com.google.android.adservices.api    E  Failed to find AdServices service
```
I also doubled checked device config is accurate:
```
+ adb shell device_config get adservices ppapi_app_allow_list
*
+ adb shell device_config get adservices ppapi_app_signature_allow_list
*
+ adb shell device_config get adservices adservice_system_service_enabled
true
+ adb shell device_config get adservices adservice_enabled
true
+ adb shell device_config get adservices adservice_enable_status
true
+ adb shell device_config get adservices global_kill_switch
false
+ adb shell device_config get adservices disable_sdk_sandbox
false
+ adb shell device_config get adservices mdd_measurement_manifest_file_url
https://www.gstatic.com/mdi-serving/r.......
```
The service seems to be up since its responding to forcing it's jobs like:
`adb shell cmd jobscheduler run -f com.google.android.adservices.api  14`
which works

What could be the issue?

**Comment by erintwalsh** [comment]
Hi @levyitay, thanks for reporting the issue! Would you mind letting us know if you are experiencing this on a Developer Preview or Beta release?

**Comment by erintwalsh** [comment]
@levyitay thanks for the quick response! Just to check, are you using Developer Preview 7? (You can check this in the SDK Manager, in the `Android TiramisuPrivacySandboxPreview` row in the `Revision` column it will say revision 9 for DP7)

**Comment by levyitay** [comment]
I believe so
<img width="671" alt="image" src="https://user-images.githubusercontent.com/326684/215875946-8585841c-59c5-4452-9305-ac2471d2c862.png">

**Comment by erintwalsh** [comment]
Thanks, @levyitay! Would you mind following a few more steps to help us debug the issue? 

1. Is the AdId kill switch turned off on your device? You can check the status by running `adb shell device_config get adservices adid_kill_switch` and if it's on, you can turn it off by running `adb shell device_config set adservices adid_kill_switch false`.

2. What is the GMSCore version of your device? You can find out by running `adb shell dumpsys package com.google.android.gms | grep version`

3. Would you mind uploading verbose logs? You can get them by running `adb shell setprop log.tag.adservices VERBOSE && adb logcat -s "adservices"`

Thank you!!

**Comment by levyitay** [comment]
@erintwalsh 
On emulator:
1. yes it was off
2. gms version output:
```
    version:
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
        fd7c62f com.google.android.gms/.ads.measurement.GmpConversionTrackingBrokerService filter 49be43c
    versionCode=230313044 minSdk=31 targetSdk=33
    versionName=23.03.13 (190400-503260631)
    signatures=PackageSignatures{528da90 version:3, signatures:[98deb0ca], past signatures:[e3ca78d8 flags: 17, 98deb0ca flags: 17]}
    versionCode=221821044 minSdk=31 targetSdk=33
    versionName=22.18.21 (190400-453244992)
    signatures=PackageSignatures{528da90 version:3, signatures:[98deb0ca], past signatures:[e3ca78d8 flags: 17, 98deb0ca flags: 17]}

```

3.  logs while executing register source (click) 
```
02-01 11:00:24.569 15714 15714 D adservices: registerSource
02-01 11:00:24.588  5965  6496 V adservices: Process 10162 has importance 100 comparing with threshold of 125.
02-01 11:00:24.590  5965  6496 V adservices: AdIdWorker.getAdId for com.is.levelplay.test, 10162
02-01 11:00:24.590  5965  6496 E adservices: Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
02-01 11:00:24.590  5965  6496 E adservices: Failed to find AdServices service
02-01 11:00:24.594  5965  6497 V adservices: Process 10162 has importance 100 comparing with threshold of 125.
02-01 11:00:24.605  5965  6497 D adservices: MeasurementDao: insertAsyncRegistration: rowId=7
```

On device (pixel 5 with Build TRA4.221021.001.A1):

1. adid_kill_switch is off
2. 
```
      version:
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
          Scheme: "version"
        38fe9f9 com.google.android.gms/.ads.measurement.GmpConversionTrackingBrokerService filter d26ad3e
    versionCode=230313044 minSdk=31 targetSdk=33
    versionName=23.03.13 (190400-503260631)
    signatures=PackageSignatures{fa58c15 version:3, signatures:[98deb0ca], past signatures:[e3ca78d8 flags: 17, 98deb0ca flags: 17]}
    versionCode=221821045 minSdk=31 targetSdk=33
    versionName=22.18.21 (190408-453244992)
    signatures=PackageSignatures{4512d1b version:0, signatures:[], past signatures:[]}
```

3. while doing register source:
```
02-01 11:03:50.374 13907 13907 D adservices: registerSource
02-01 11:03:50.376 13907 13907 D adservices: bindService: android.adservices.ADID_SERVICE
02-01 11:03:50.385 13907 13907 D adservices: bindService() started...
02-01 11:03:50.390 13907 13931 D adservices: onServiceConnected android.adservices.ADID_SERVICE
02-01 11:03:50.393 17961   829 V adservices: Process 10249has importance 100 comparing with threshold of 125
02-01 11:03:50.394 17961   829 V adservices: AdIdWorker.getAdId for com.is.levelplay.test, 10249
02-01 11:03:50.394 17961   829 E adservices: Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
02-01 11:03:50.394 17961   829 E adservices: Failed to find AdServices service
02-01 11:03:50.396 13907 13976 D adservices: bindService: android.adservices.MEASUREMENT_SERVICE
02-01 11:03:50.399 13907 13976 D adservices: bindService() started...
02-01 11:03:50.402 17961 17961 D adservices: AggregateReportingJobService already scheduled, skipping reschedule
02-01 11:03:50.402 17961 17961 D adservices: AggregateFallbackReportingJobService already scheduled, skipping reschedule
02-01 11:03:50.403 17961 17961 D adservices: AttributionJobService already scheduled, skipping reschedule
02-01 11:03:50.403 17961 17961 D adservices: EventReportingJobService already scheduled, skipping reschedule
02-01 11:03:50.404 17961 17961 D adservices: EventFallbackReportingJobService already scheduled, skipping reschedule
02-01 11:03:50.404 17961 17961 D adservices: DeleteExpiredJobService already scheduled, skipping reschedule
02-01 11:03:50.404 17961 17961 D adservices: Maintenance Periodic Task has been scheduled with same parameters, skip rescheduling!
02-01 11:03:50.405 17961 17961 D adservices: Maintenance Periodic Task has been scheduled with same parameters, skip rescheduling!
02-01 11:03:50.405 17961 17961 D adservices: Maintenance Periodic Task has been scheduled with same parameters, skip rescheduling!
02-01 11:03:50.405 17961 17961 D adservices: Maintenance Periodic Task has been scheduled with same parameters, skip rescheduling!
02-01 11:03:50.406 13907 13931 D adservices: onServiceConnected android.adservices.MEASUREMENT_SERVICE
02-01 11:03:50.411 17961 32325 V adservices: Process 10249has importance 100 comparing with threshold of 125
02-01 11:03:51.025 17961 32325 D adservices: MeasurementImpl: register: success=false
```

register trigger:
```
-01 11:05:57.169 13907 13907 D adservices: registerTrigger
02-01 11:05:57.173 17961 28706 V adservices: Process 10249has importance 100 comparing with threshold of 125
02-01 11:05:57.173 17961 28706 V adservices: AdIdWorker.getAdId for com.is.levelplay.test, 10249
02-01 11:05:57.174 17961 28706 E adservices: Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
02-01 11:05:57.174 17961 28706 E adservices: Failed to find AdServices service
02-01 11:05:57.181 17961   828 V adservices: Process 10249has importance 100 comparing with threshold of 125
02-01 11:05:57.793 17961   828 D adservices: Response code = 400
02-01 11:05:57.794 17961   828 D adservices: MeasurementImpl: register: success=false
```

**Comment by levyitay** [comment]
@erintwalsh Did we figure this one out?

**Comment by cshmerling** [comment]
Sorry for the delay, jumping in to this issue a bit late so please excuse me if my question is out of date.

We believe the issue comes from your device having not received a config rollout yet. It appears it's harder to get working on an emulator, so using your physical device, can you try to start the missing service via adb:

```
adb shell am startservice com.google.android.gms/.ads.identifier.service.AdIdProviderService
```

And let me know what the output is? Should see something like

```
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.gms/.ads.identifier.service.AdIdProviderService }
```

But if it fails, will have an additional `Error: Not found; no service started` line. If it does fail will need to dig a bit more on our side.

**Comment by levyitay** [comment]
yeah I got: 
```
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.gms/.ads.identifier.service.AdIdProviderService }
Error: Not found; no service started.
```
FYI I'm on `TRA4.221021.001.A1` should I update? If so to what version?

**Comment by RonShub** [comment]
Hi, I'm getting the same error `Failed to find AdServices service` and see the exact same output as @levyitay 
I'm using a pixel4 emulator with TiramisuPrivacySandbox SDK revision 9.

Any updates regarding the issue? @erintwalsh Is it expected to work on a physical device?

**Comment by shen714** [comment]
Hi, I am testing the developer preview and is facing the same problem on both emulator and physical device.

> 2023-02-22 17:51:28.233  7206-7222  adservices              pid-7206                             E  Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
> 2023-02-22 17:51:28.233  7206-7222  adservices              pid-7206                             E  Failed to find AdServices service
> 2023-02-22 17:51:28.344  7206-7226  adservices              pid-7206                             E  Caller is not authorized.

Wondering if there is some guidance on how to proceed. Thanks!

**Comment by olegkushniriov** [comment]
Hey, I have same issue running on Pixel 5
```
Process 10251 has importance 100 comparing with threshold of 125.
adservices: AdIdWorker.getAdId for com.android_privacy_sandbox_sample, 10251
adservices: Failed to find resolveInfo for adServices service. Intent action: android.adservices.adid.AdIdProviderService
adservices: Failed to find AdServices service
adservices: Process 10251 has importance 100 comparing with threshold of 125.
adservices: MeasurementDao: insertAsyncRegistration: rowId=7
```
While running 
`Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.gms/.ads.identifier.service.AdIdProviderService }`
responds with
`Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.google.android.gms/.ads.identifier.service.AdIdProviderService }
Error: Not found; no service started.`

**Comment by erintwalsh** [comment]
Hi everyone! We greatly appreciate the logs and insights posted here as we worked on the issue. An update has started to roll out, so you should be seeing this issue resolved shortly on both physical devices and emulators (exact time will vary depending on device and network connectivity). Thank you for bearing with us!

**Comment by levyitay** [comment]
@erintwalsh @cshmerling 
Which versions of gms should we be on the lookout for? 
I just installed Preview 7 on Pixel 5 and still encounter the same issue.

**Comment by pazlavi** [comment]
@erintwalsh @cshmerling 
I still have this issue with Pixel 6 (running preview 7) and Pixel 5 (running beta 2)

**Comment by erintwalsh** [comment]
Hi all, 

If you are still experiencing the issue, can you please provide the version code on your device? You can find this by going to Settings > About phone > Build number. 

Can you also confirm that you have updated to the latest version of Developer Preview 7, or Beta 2? 

Instructions to update to the latest Developer Preview 7 on an emulator: 

- Open the SDK manager in Android Studio
- Check the box that says “Show Package Details” (1)
- In the SDKPlatforms tab, under Android TiramisuPrivacySandboxPreivew, make sure the SDK and System Images all have a ‘9’ in the Revision Column. (2)
- If a SDK or System Image is out of date, check the box to the left (3) and click “Apply” (4) at the bottom right to download the update
- After you update, please restart your emulated device, run your app, and try calling the APIs again

![update-dp](https://user-images.githubusercontent.com/17595592/228373473-7bacd1cc-a0a6-450f-b03b-c94c8bae6211.png)

Instructions to update to the latest Beta 2 on an emulator: 
- Open the SDK manager in Android Studio
- Check the box that says “Show Package Details” 
- In the SDKPlatforms tab, make sure that all SDK and System Images under Android 13.0 (Tiramisu), Extension Level 5 are up to date 
- After you update, please restart your emulated device, run your app, and try calling the APIs again

![update-beta](https://user-images.githubusercontent.com/17595592/228373491-1591e671-932a-4084-899b-0bb3d0deb153.png)

**Comment by erintwalsh** [comment]
Hi @RonShub, @levyitay, and @pazlavi, if you're still experiencing this issue, would you mind following these steps and then try calling the API again? 

Reset your allow list by running the commands
* adb shell device_config delete adservices ppapi_app_allow_list

* adb shell device_config put adservices ppapi_app_allow_list [your app package name]


Note: you will need to use the 'put' command for each app package name you are testing with.

**Comment by levyitay** [comment]
@erintwalsh when I first tried it I got the following error: 
```
---------------------------- PROCESS STARTED (17903) for package com.is.levelplay.test ----------------------------
2023-03-31 13:17:04.400 17903-17903 adservices              pid-17903                            D  registerSource
2023-03-31 13:17:04.408 14128-14128 adservices              pid-14128                            E  Measurement API is disabled
2023-03-31 13:17:04.409 14128-14128 adservices              pid-14128                            E  Measurement API is disabled
2023-03-31 13:17:04.409 17903-17921 adservices              pid-17903                            E  onNullBinding android.adservices.MEASUREMENT_SERVICE
2023-03-31 13:17:04.414 17903-17903 adservices              pid-17903                            E  Failed binding to measurement service: java.lang.IllegalStateException: Service is not available.
---------------------------- PROCESS ENDED (17903) for package com.is.levelplay.test ----------------------------
```
Then I ran our script that supposed to setup my device for Privacy Sandbox (I removed manifest url just for posting this)

```
#!/bin/bash

adb=$(which adb)

echo Configuring FLEDGE JS isolate enforce max heap size...
$adb shell 'device_config put adservices fledge_js_isolate_enforce_max_heap_size false'

echo Configuring PPAPI app allow list...
$adb shell 'device_config put adservices ppapi_app_allow_list "com.is.levelplay.test"'
$adb shell 'device_config put adservices ppapi_app_signature_allow_list "com.is.levelplay.test"'

echo "Disable Fledge API enrollment check"
$adb shell "device_config put adservices disable_fledge_enrollment_check true"

echo "Disable Topiscs API enrollment check"
$adb shell setprop debug.adservices.disable_topics_enrollment_check true

echo Configuring global kill switch...
$adb shell 'device_config put adservices global_kill_switch false'

echo Enabling SDK sandbox...
$adb shell 'device_config put adservices disable_sdk_sandbox false'
$adb shell cmd sdk_sandbox set-state --enabled

echo Overriding the enrollment list...
$adb shell 'device_config put adservices mdd_measurement_manifest_file_url "PUT_MANIFEST_URL_HERE"'

echo The measurement URL has been override to
$adb shell 'device_config get adservices mdd_measurement_manifest_file_url'

echo "Enabled Ad Services"
$adb shell 'device_config put adservices adservice_system_service_enabled true'
$adb shell 'device_config put adservices adservice_enabled true'

echo "Disable User Consent"
$adb shell 'setprop debug.adservices.consent_manager_debug_mode true'

echo Configurations are finished! 🌟
exit
```

And got this:
*NOTE: I removed `enrollment_id` and `registration_uri` as security precaution
 
```
---------------------------- PROCESS STARTED (19286) for package com.is.levelplay.test ----------------------------
2023-03-31 13:21:47.269 19286-19286 adservices              pid-19286                            D  registerSource
2023-03-31 13:21:47.308 14128-18409 adservices              pid-14128                            E  Caller is not authorized.
```

I waited few minutes and saw that ad services service started an update from the enrollment url so I decided to try again and got this:

```
023-03-31 13:25:08.790  2031-8158  ProcessStats            pid-2031                             W  Tracking association SourceState{c815e1a com.is.levelplay.test/10256 Top #17140} whose proc state 1 is better than process ProcessState{c970f5e com.google.android.adservices.api/10228 pkg=com.google.android.adservices.api} proc state 3 (877 skipped)
2023-03-31 13:25:19.220  2031-8158  ProcessStats            pid-2031                             W  Tracking association SourceState{c815e1a com.is.levelplay.test/10256 Top #17209} whose proc state 1 is better than process ProcessState{c970f5e com.google.android.adservices.api/10228 pkg=com.google.android.adservices.api} proc state 3 (226 skipped)
2023-03-31 13:26:19.729 19286-19286 adservices              pid-19286                            D  registerSource
2023-03-31 13:26:19.765 14128-18611 SQLiteDatabase          pid-14128                            E  Error inserting registrant=android-app://com.is.levelplay.test os_destination=null last_processing_time=1680294379761 web_destination=null retry_count=0 top_origin=android-app://com.is.levelplay.test redirect_count=0 redirect_type=1 debug_key_allowed=false source_type=1 _id=c1c7c720-a224-49ea-8a6c-eb359a96302e type=0 registration_uri*******verified_destination=null enrollment_id=****** request_time=1680294379759 ad_id_permission=true
                                                                                                    android.database.sqlite.SQLiteException: table msmt_async_registration_contract has no column named ad_id_permission (code 1 SQLITE_ERROR): , while compiling: INSERT INTO msmt_async_registration_contract(registrant,os_destination,last_processing_time,web_destination,retry_count,top_origin,redirect_count,redirect_type,debug_key_allowed,source_type,_id,type,registration_uri,verified_destination,enrollment_id,request_time,ad_id_permission) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                                                                                                    	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                                    	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
                                                                                                    	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
                                                                                                    	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
                                                                                                    	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
                                                                                                    	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:34)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1866)
                                                                                                    	at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1737)
                                                                                                    	at com.android.adservices.data.measurement.MeasurementDao.insertAsyncRegistration(MeasurementDao.java:1847)
                                                                                                    	at com.android.adservices.service.measurement.registration.EnqueueAsyncRegistration.insertAsyncRegistration(EnqueueAsyncRegistration.java:228)
                                                                                                    	at com.android.adservices.service.measurement.registration.EnqueueAsyncRegistration.lambda$appSourceOrTriggerRegistrationRequest$0(EnqueueAsyncRegistration.java:68)
                                                                                                    	at com.android.adservices.service.measurement.registration.EnqueueAsyncRegistration.$r8$lambda$qDeOSQVCgyhGqZZRsg9r9NYGSEE(Unknown Source:0)
                                                                                                    	at com.android.adservices.service.measurement.registration.EnqueueAsyncRegistration$$ExternalSyntheticLambda0.accept(Unknown Source:11)
                                                                                                    	at com.android.adservices.data.measurement.DatastoreManager.lambda$runInTransaction$0(DatastoreManager.java:113)
                                                                                                    	at com.android.adservices.data.measurement.DatastoreManager.$r8$lambda$H1c24kOxtwIVwS1Iwri8szpzOBM(Unknown Source:0)
                                                                                                    	at com.android.adservices.data.measurement.DatastoreManager$$ExternalSyntheticLambda0.apply(Unknown Source:2)
                                                                                                    	at com.android.adservices.data.measurement.DatastoreManager.runInTransactionWithResult(DatastoreManager.java:88)
                                                                                                    	at com.android.adservices.data.measurement.DatastoreManager.runInTransaction(DatastoreManager.java:112)
                                                                                                    	at com.android.adservices.service.measurement.registration.EnqueueAsyncRegistration.appSourceOrTriggerRegistrationRequest(EnqueueAsyncRegistration.java:59)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementImpl.register(MeasurementImpl.java:154)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl.lambda$register$0(MeasurementServiceImpl.java:171)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl.$r8$lambda$rFwFWA568upDNp2Z8tuaApyoP-I(Unknown Source:0)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl$$ExternalSyntheticLambda16.accept(Unknown Source:6)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl.performRegistration(MeasurementServiceImpl.java:523)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl.lambda$register$2(MeasurementServiceImpl.java:169)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl.$r8$lambda$va29zmFGYHF6VWq9jqvIapJsAmU(Unknown Source:0)
                                                                                                    	at com.android.adservices.service.measurement.MeasurementServiceImpl$$ExternalSyntheticLambda0.run(Unknown Source:16)
2023-03-31 13:26:19.765 14128-18611 adservices              pid-14128                            E  DatastoreException thrown during transaction: com.android.adservices.data.measurement.DatastoreException: Async Registration insertion failed.
2023-03-31 13:27:16.442  2031-2338  ProcessStats            pid-2031                             W  Tracking association SourceState{c815e1a com.is.levelplay.test/10256 Top #19806} whose proc state 1 is better than process ProcessState{c970f5e com.google.android.adservices.api/10228 pkg=com.google.android.adservices.api} proc state 3 (622 skipped)
2023-03-31 13:27:36.465  2031-2338  ProcessStats            pid-2031                             W  Tracking association SourceState{c815e1a com.is.levelplay.test/10256 Top #20147} whose proc state 1 is better than process ProcessState{c970f5e com.google.android.adservices.api/10228 pkg=com.google.android.adservices.api} proc state 3 (2583 skipped)
2023-03-31 13:27:46.669  2031-8969  ProcessStats            pid-2031                             W  Tracking association SourceState{c815e1a com.is.levelplay.test/10256 Top #20184} whose proc state 1 is better than process ProcessState{c970f5e com.google.android.adservices.api/10228 pkg=com.google.android.adservices.api} proc state 3 (287 skipped)

```

**Comment by kwanmacher** [comment]
We are seeing the exact same error... Curious if anyone has successfully called the attribution reporting API, and if so, what did you do/change to make this happen?

**Comment by RonShub** [comment]
Hey,
I've restarted the app after validating that the revision is ‘9’ on the emulator's TiramisuPrivacySandboxPreview system image, and updated the `ppapi_app_allow_list` with the relevant package name.
But still still getting the same errors as before - 
`Failed to find resolveInfo for adServices`
`Failed to find AdServices service`
`Caller is not authorized.`

**Comment by levyitay** [comment]
@erintwalsh Any update on that stack trace and issue from my last comment?

**Comment by erintwalsh** [comment]
Hi everyone, 

Thanks for your continued feedback, stack traces, and patience! We have made a few updates that will hopefully be helpful. Would you mind making sure you have the latest commits from this GitHub project, testing on a fresh emulator or clean install on a device, and making sure all the steps on [this page](https://developer.android.com/design-for-safety/privacy-sandbox/setup-device-access?version=preview) are followed?
