### ISSUE TITLE
No direct method <init>() in AdSelectionConfig$Builder while running FledgeKotlin demo

### ISSUE THREAD

**Issue by flowenol** [android/privacy-sandbox-samples#9]
Hi,

I am trying to run the demo according to the instructions from README, but once I specify the `biddingUrl` and `scoringUrl` parameters, the application crashes immediately:

```
06-20 20:32:53.841  6335  6335 E AndroidRuntime: FATAL EXCEPTION: main
06-20 20:32:53.841  6335  6335 E AndroidRuntime: Process: com.example.adservices.samples.fledge.sampleapp, PID: 6335
06-20 20:32:53.841  6335  6335 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>()V in class Landroid/adservices/adselection/AdSelectionConfig$Builder; or its super classes (declaration of 'android.adservices.adselection.AdSelectionConfig$Builder' appears in /apex/com.android.adservices/javalib/framework-adservices.jar)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at com.example.adservices.samples.fledge.sampleapp.AdSelectionWrapper.<init>(AdSelectionWrapper.kt:121)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at com.example.adservices.samples.fledge.sampleapp.MainActivity.onCreate(MainActivity.kt:76)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8268)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:8247)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1371)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3667)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3823)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7886)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
06-20 20:32:53.841  6335  6335 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

I am running TiramisuPrivacySandbox SDK revision 3 on a Pixel 4 emulated device. What is odd, when I hook up to the app with the debugger and evaluate the following code snippet from `AdSelectionWrapper` class in IDE:

```
AdSelectionConfig.Builder()
      .setSeller(seller)
      .setDecisionLogicUrl(decisionUrl)
      .setCustomAudienceBuyers(buyers)
      .setAdSelectionSignals(JSONObject().toString())
      .setSellerSignals(JSONObject().toString())
      .setPerBuyerSignals(buyers.stream()
                            .collect(Collectors.toMap(
                              { buyer: String? -> buyer },
                              { JSONObject().toString() })))
      .setContextualAds(ArrayList())
      .build()
```
the AdSelectionConfig object is created without issues, but when I resume the application it crashes as described above. 

I will be grateful for any hints on that.

**Comment by flowenol** [comment]
It turned out that the outdated system image was the culprit. Once I refreshed, the problem disappeared.
